import axios from "axios";

const instance = axios.create({
  //backend api endpoint generated by firebase cloud functions
  baseURL: "https://us-central1-mama-zon.cloudfunctions.net/api",
  //localhost backend url : "http://localhost:5001/mama-zon/us-central1/api",
});

export default instance;
